name: Upload static files to S3 bucket

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Configure AWS details
              uses: aws-actions/configure-aws-credentials@v2
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ap-southeast-2

            - name: Run npm i to install dependencies
              run: npm install

            - name: Run unit tests
              run: npm run test

            - name: Build app
              run: |
                REACT_APP_API_PROXY_HOST=${{ secrets.REACT_APP_API_PROXY_HOST }} 
                REACT_APP_API_PROXY_USER=${{ secrets.REACT_APP_API_PROXY_USER }} 
                REACT_APP_API_PROXY_PASS=${{ secrets.REACT_APP_API_PROXY_PASS }} 
                npm run build

            - name: Deploy assets to S3
              run: aws s3 sync ./build/ s3://${{ secrets.BUCKET }} --delete
